### ISSUE TITLE
head1，head2,..visual attention hot map

### ISSUE THREAD

**Issue by RC-Qiao** [mobulan/IELT#3]
可以上传一下可视化attention map of each head的代码么

**Comment by mobulan** [comment]
我已经添加了可视化代码，使用方法：1》通过训练获得checkpoint.bin，2》修改setup.py，注释第5行，激活第6行（除非将可视化文件放在外面，暂时没发现更好的办法）3》打开[HeadMapVisualize](https://github.com/mobulan/IELT/tree/main/visualize/HeadMapVisualize.py)，修改main函数中图像和检查点的路径，以及第21行的保存路径 4》运行[HeadMapVisualize](https://github.com/mobulan/IELT/tree/main/visualize/HeadMapVisualize.py) `python visualize/HeadMapVisualize.py`
