### ISSUE TITLE
using ilet modul

### ISSUE THREAD

**Issue by mtkhrns** [mobulan/IELT#4]
Hello, can you provide code for using only the multihead voting, CLR, or DS module?

**Comment by mobulan** [comment]
Thank you for your interest in our work. I have been very busy recently, so the reply has been slightly delayed. I am sorry for that.
You can change the `cam`, and `dsm` to `False` in the `configs/{dataset}.yaml` to disable clr and ds respectively. If you want to disable mhv, you can chage the `baseline_model` to `True`. If you are still confused, please feel free to ask
