### ISSUE TITLE
CUB dataset can't running and gdrive link can't be accesed

### ISSUE THREAD

**Issue by wesrambi** [mobulan/IELT#7]
I have an error while running for CUB_200_2011, and the error message goes like this 

RuntimeError: The MD5 checksum of the download file /workspace/IELTS/dataset/CUB_200_2011/CUB_200_2011.tgz does not match the one on record.Please delete the file and try again. If the issue persists, please report this to torchvision at https://github.com/pytorch/vision/issues.

then there's gdrive link that shows so i can download the tgz or the dataset but it can't
this is the link that shown 
![error issue](https://github.com/mobulan/IELT/assets/75151812/7edead0e-d103-4797-bc01-f560ac6d6ed6)
(https://drive.usercontent.google.com/download)

**Comment by mobulan** [comment]
You should first unzip the CUB dataset. I uploaded the dataset to [Huggging Face](https://huggingface.co/datasets/Mobulan/CUB-200-2011), you can download it and unzip it to the dataset root directory.

**Comment by wesrambi** [comment]
Thankyou so much!!

anyway i’m doing some research about your IELT proposed method, but I’m
focusing on the final prediction (assist logits & refined features).

have you any recomendation about how to improve the accuracy from the final
prediction side??🙏🏼
thanks before🙏🏼

your new friend, Wesli

**Comment by wesrambi** [comment]
thankyouu so much!! 
it works!
